from typing import List, Any
from .ir import DatasetIR, AttributeType

def serialize_arff_value(val: Any, attr_type: AttributeType) -> str:
    if val is None:
        return "?"
    
    s_val = str(val).strip()
    if s_val == "" or s_val == "?":
        return "?"

    if attr_type == AttributeType.NUMERIC:
        # Check if int or float
        try:
            f = float(s_val)
            if f.is_integer() and "." not in s_val and "e" not in s_val.lower():
                return str(int(f))
            return s_val
        except ValueError:
            return s_val

    # For string or nominal: quote if it contains space, comma, single quote, double quote, or special chars
    need_quote = any(c in s_val for c in [" ", ",", "'", '"', "\t", "{", "}", "%"])
    if need_quote:
        clean = s_val.replace("'", "\\'")
        return f"'{clean}'"
    
    return s_val

def write_to_arff(dataset: DatasetIR) -> str:
    lines: List[str] = []
    
    # Header comments
    lines.append("% Generated by NITK File Converter System (WEKA 3.8+ Compatible)")
    lines.append(f"% Total Instances: {dataset.instance_count}")
    lines.append(f"% Total Attributes: {dataset.attribute_count}")
    lines.append("")

    # @relation declaration
    rel_name = dataset.relation_name.strip()
    if " " in rel_name:
        lines.append(f"@relation '{rel_name}'")
    else:
        lines.append(f"@relation {rel_name}")
    lines.append("")

    # @attribute declarations
    for attr in dataset.attributes:
        lines.append(attr.to_arff_declaration())
    lines.append("")

    # @data section
    lines.append("@data")
    for instance in dataset.instances:
        row_tokens = []
        for val, attr in zip(instance, dataset.attributes):
            row_tokens.append(serialize_arff_value(val, attr.type))
        lines.append(",".join(row_tokens))

    lines.append("")
    return "\n".join(lines)
